// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/kgoettler/twe/pkg/timewarrior"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTimewarriorBackend creates a new instance of MockTimewarriorBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimewarriorBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimewarriorBackend {
	mock := &MockTimewarriorBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTimewarriorBackend is an autogenerated mock type for the TimewarriorBackend type
type MockTimewarriorBackend struct {
	mock.Mock
}

type MockTimewarriorBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimewarriorBackend) EXPECT() *MockTimewarriorBackend_Expecter {
	return &MockTimewarriorBackend_Expecter{mock: &_m.Mock}
}

// Annotate provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Annotate(id int, annotation string) error {
	ret := _mock.Called(id, annotation)

	if len(ret) == 0 {
		panic("no return value specified for Annotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(id, annotation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTimewarriorBackend_Annotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Annotate'
type MockTimewarriorBackend_Annotate_Call struct {
	*mock.Call
}

// Annotate is a helper method to define mock.On call
//   - id int
//   - annotation string
func (_e *MockTimewarriorBackend_Expecter) Annotate(id interface{}, annotation interface{}) *MockTimewarriorBackend_Annotate_Call {
	return &MockTimewarriorBackend_Annotate_Call{Call: _e.mock.On("Annotate", id, annotation)}
}

func (_c *MockTimewarriorBackend_Annotate_Call) Run(run func(id int, annotation string)) *MockTimewarriorBackend_Annotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTimewarriorBackend_Annotate_Call) Return(err error) *MockTimewarriorBackend_Annotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTimewarriorBackend_Annotate_Call) RunAndReturn(run func(id int, annotation string) error) *MockTimewarriorBackend_Annotate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Delete(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTimewarriorBackend_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTimewarriorBackend_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockTimewarriorBackend_Expecter) Delete(id interface{}) *MockTimewarriorBackend_Delete_Call {
	return &MockTimewarriorBackend_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTimewarriorBackend_Delete_Call) Run(run func(id int)) *MockTimewarriorBackend_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTimewarriorBackend_Delete_Call) Return(err error) *MockTimewarriorBackend_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTimewarriorBackend_Delete_Call) RunAndReturn(run func(id int) error) *MockTimewarriorBackend_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Export provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Export(args ...string) ([]timewarrior.Interval, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 []timewarrior.Interval
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...string) ([]timewarrior.Interval, error)); ok {
		return returnFunc(args...)
	}
	if returnFunc, ok := ret.Get(0).(func(...string) []timewarrior.Interval); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timewarrior.Interval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...string) error); ok {
		r1 = returnFunc(args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTimewarriorBackend_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockTimewarriorBackend_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - args ...string
func (_e *MockTimewarriorBackend_Expecter) Export(args ...interface{}) *MockTimewarriorBackend_Export_Call {
	return &MockTimewarriorBackend_Export_Call{Call: _e.mock.On("Export",
		append([]interface{}{}, args...)...)}
}

func (_c *MockTimewarriorBackend_Export_Call) Run(run func(args ...string)) *MockTimewarriorBackend_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockTimewarriorBackend_Export_Call) Return(intervals []timewarrior.Interval, err error) *MockTimewarriorBackend_Export_Call {
	_c.Call.Return(intervals, err)
	return _c
}

func (_c *MockTimewarriorBackend_Export_Call) RunAndReturn(run func(args ...string) ([]timewarrior.Interval, error)) *MockTimewarriorBackend_Export_Call {
	_c.Call.Return(run)
	return _c
}

// Modify provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Modify(id int, field string, value string) error {
	ret := _mock.Called(id, field, value)

	if len(ret) == 0 {
		panic("no return value specified for Modify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = returnFunc(id, field, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTimewarriorBackend_Modify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modify'
type MockTimewarriorBackend_Modify_Call struct {
	*mock.Call
}

// Modify is a helper method to define mock.On call
//   - id int
//   - field string
//   - value string
func (_e *MockTimewarriorBackend_Expecter) Modify(id interface{}, field interface{}, value interface{}) *MockTimewarriorBackend_Modify_Call {
	return &MockTimewarriorBackend_Modify_Call{Call: _e.mock.On("Modify", id, field, value)}
}

func (_c *MockTimewarriorBackend_Modify_Call) Run(run func(id int, field string, value string)) *MockTimewarriorBackend_Modify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTimewarriorBackend_Modify_Call) Return(err error) *MockTimewarriorBackend_Modify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTimewarriorBackend_Modify_Call) RunAndReturn(run func(id int, field string, value string) error) *MockTimewarriorBackend_Modify_Call {
	_c.Call.Return(run)
	return _c
}

// Retag provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Retag(id int, tags []string) error {
	ret := _mock.Called(id, tags)

	if len(ret) == 0 {
		panic("no return value specified for Retag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, []string) error); ok {
		r0 = returnFunc(id, tags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTimewarriorBackend_Retag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retag'
type MockTimewarriorBackend_Retag_Call struct {
	*mock.Call
}

// Retag is a helper method to define mock.On call
//   - id int
//   - tags []string
func (_e *MockTimewarriorBackend_Expecter) Retag(id interface{}, tags interface{}) *MockTimewarriorBackend_Retag_Call {
	return &MockTimewarriorBackend_Retag_Call{Call: _e.mock.On("Retag", id, tags)}
}

func (_c *MockTimewarriorBackend_Retag_Call) Run(run func(id int, tags []string)) *MockTimewarriorBackend_Retag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTimewarriorBackend_Retag_Call) Return(err error) *MockTimewarriorBackend_Retag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTimewarriorBackend_Retag_Call) RunAndReturn(run func(id int, tags []string) error) *MockTimewarriorBackend_Retag_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Stop(stopTime *string) error {
	ret := _mock.Called(stopTime)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*string) error); ok {
		r0 = returnFunc(stopTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTimewarriorBackend_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockTimewarriorBackend_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - stopTime *string
func (_e *MockTimewarriorBackend_Expecter) Stop(stopTime interface{}) *MockTimewarriorBackend_Stop_Call {
	return &MockTimewarriorBackend_Stop_Call{Call: _e.mock.On("Stop", stopTime)}
}

func (_c *MockTimewarriorBackend_Stop_Call) Run(run func(stopTime *string)) *MockTimewarriorBackend_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *string
		if args[0] != nil {
			arg0 = args[0].(*string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTimewarriorBackend_Stop_Call) Return(err error) *MockTimewarriorBackend_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTimewarriorBackend_Stop_Call) RunAndReturn(run func(stopTime *string) error) *MockTimewarriorBackend_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Track(interval timewarrior.Interval) error {
	ret := _mock.Called(interval)

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(timewarrior.Interval) error); ok {
		r0 = returnFunc(interval)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTimewarriorBackend_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockTimewarriorBackend_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - interval timewarrior.Interval
func (_e *MockTimewarriorBackend_Expecter) Track(interval interface{}) *MockTimewarriorBackend_Track_Call {
	return &MockTimewarriorBackend_Track_Call{Call: _e.mock.On("Track", interval)}
}

func (_c *MockTimewarriorBackend_Track_Call) Run(run func(interval timewarrior.Interval)) *MockTimewarriorBackend_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 timewarrior.Interval
		if args[0] != nil {
			arg0 = args[0].(timewarrior.Interval)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTimewarriorBackend_Track_Call) Return(err error) *MockTimewarriorBackend_Track_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTimewarriorBackend_Track_Call) RunAndReturn(run func(interval timewarrior.Interval) error) *MockTimewarriorBackend_Track_Call {
	_c.Call.Return(run)
	return _c
}

// Undo provides a mock function for the type MockTimewarriorBackend
func (_mock *MockTimewarriorBackend) Undo() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Undo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTimewarriorBackend_Undo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Undo'
type MockTimewarriorBackend_Undo_Call struct {
	*mock.Call
}

// Undo is a helper method to define mock.On call
func (_e *MockTimewarriorBackend_Expecter) Undo() *MockTimewarriorBackend_Undo_Call {
	return &MockTimewarriorBackend_Undo_Call{Call: _e.mock.On("Undo")}
}

func (_c *MockTimewarriorBackend_Undo_Call) Run(run func()) *MockTimewarriorBackend_Undo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTimewarriorBackend_Undo_Call) Return(err error) *MockTimewarriorBackend_Undo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTimewarriorBackend_Undo_Call) RunAndReturn(run func() error) *MockTimewarriorBackend_Undo_Call {
	_c.Call.Return(run)
	return _c
}
