// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBackendCmdTimecard creates a new instance of MockBackendCmdTimecard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackendCmdTimecard(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackendCmdTimecard {
	mock := &MockBackendCmdTimecard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackendCmdTimecard is an autogenerated mock type for the BackendCmdTimecard type
type MockBackendCmdTimecard struct {
	mock.Mock
}

type MockBackendCmdTimecard_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackendCmdTimecard) EXPECT() *MockBackendCmdTimecard_Expecter {
	return &MockBackendCmdTimecard_Expecter{mock: &_m.Mock}
}

// Report provides a mock function for the type MockBackendCmdTimecard
func (_mock *MockBackendCmdTimecard) Report(args ...string) (io.Reader, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Report")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...string) (io.Reader, error)); ok {
		return returnFunc(args...)
	}
	if returnFunc, ok := ret.Get(0).(func(...string) io.Reader); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...string) error); ok {
		r1 = returnFunc(args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackendCmdTimecard_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type MockBackendCmdTimecard_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - args ...string
func (_e *MockBackendCmdTimecard_Expecter) Report(args ...interface{}) *MockBackendCmdTimecard_Report_Call {
	return &MockBackendCmdTimecard_Report_Call{Call: _e.mock.On("Report",
		append([]interface{}{}, args...)...)}
}

func (_c *MockBackendCmdTimecard_Report_Call) Run(run func(args ...string)) *MockBackendCmdTimecard_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockBackendCmdTimecard_Report_Call) Return(reader io.Reader, err error) *MockBackendCmdTimecard_Report_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *MockBackendCmdTimecard_Report_Call) RunAndReturn(run func(args ...string) (io.Reader, error)) *MockBackendCmdTimecard_Report_Call {
	_c.Call.Return(run)
	return _c
}
