// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/kgoettler/twe/pkg/timewarrior"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackendCmdLast creates a new instance of MockBackendCmdLast. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackendCmdLast(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackendCmdLast {
	mock := &MockBackendCmdLast{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackendCmdLast is an autogenerated mock type for the BackendCmdLast type
type MockBackendCmdLast struct {
	mock.Mock
}

type MockBackendCmdLast_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackendCmdLast) EXPECT() *MockBackendCmdLast_Expecter {
	return &MockBackendCmdLast_Expecter{mock: &_m.Mock}
}

// Export provides a mock function for the type MockBackendCmdLast
func (_mock *MockBackendCmdLast) Export(args ...string) ([]timewarrior.Interval, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 []timewarrior.Interval
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...string) ([]timewarrior.Interval, error)); ok {
		return returnFunc(args...)
	}
	if returnFunc, ok := ret.Get(0).(func(...string) []timewarrior.Interval); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timewarrior.Interval)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...string) error); ok {
		r1 = returnFunc(args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackendCmdLast_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockBackendCmdLast_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - args ...string
func (_e *MockBackendCmdLast_Expecter) Export(args ...interface{}) *MockBackendCmdLast_Export_Call {
	return &MockBackendCmdLast_Export_Call{Call: _e.mock.On("Export",
		append([]interface{}{}, args...)...)}
}

func (_c *MockBackendCmdLast_Export_Call) Run(run func(args ...string)) *MockBackendCmdLast_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockBackendCmdLast_Export_Call) Return(intervals []timewarrior.Interval, err error) *MockBackendCmdLast_Export_Call {
	_c.Call.Return(intervals, err)
	return _c
}

func (_c *MockBackendCmdLast_Export_Call) RunAndReturn(run func(args ...string) ([]timewarrior.Interval, error)) *MockBackendCmdLast_Export_Call {
	_c.Call.Return(run)
	return _c
}
