// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/kgoettler/twe/pkg/timewarrior"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackendCmdImport creates a new instance of MockBackendCmdImport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackendCmdImport(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackendCmdImport {
	mock := &MockBackendCmdImport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackendCmdImport is an autogenerated mock type for the BackendCmdImport type
type MockBackendCmdImport struct {
	mock.Mock
}

type MockBackendCmdImport_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackendCmdImport) EXPECT() *MockBackendCmdImport_Expecter {
	return &MockBackendCmdImport_Expecter{mock: &_m.Mock}
}

// Track provides a mock function for the type MockBackendCmdImport
func (_mock *MockBackendCmdImport) Track(interval timewarrior.Interval) error {
	ret := _mock.Called(interval)

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(timewarrior.Interval) error); ok {
		r0 = returnFunc(interval)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackendCmdImport_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockBackendCmdImport_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - interval timewarrior.Interval
func (_e *MockBackendCmdImport_Expecter) Track(interval interface{}) *MockBackendCmdImport_Track_Call {
	return &MockBackendCmdImport_Track_Call{Call: _e.mock.On("Track", interval)}
}

func (_c *MockBackendCmdImport_Track_Call) Run(run func(interval timewarrior.Interval)) *MockBackendCmdImport_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 timewarrior.Interval
		if args[0] != nil {
			arg0 = args[0].(timewarrior.Interval)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackendCmdImport_Track_Call) Return(err error) *MockBackendCmdImport_Track_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackendCmdImport_Track_Call) RunAndReturn(run func(interval timewarrior.Interval) error) *MockBackendCmdImport_Track_Call {
	_c.Call.Return(run)
	return _c
}
