# Where should we write the GIF?
Output timecard.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 16
Set Width 1100
Set Height 600

# Type a command in the terminal.
Type "twe timecard 2025-12-01 - 2025-12-06"

# Pause for dramatic effect...
Sleep 1s

# Run the command by pressing enter.
Enter

Sleep 6s

Type "clear"
Enter
Type "twe timecard 2025-12-01 - 2025-12-06 --total-col --total-row"
Sleep 1s

Enter
Sleep 6s